version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn src.my_vacation.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run streamlit run frontend/app.py --host 0.0.0.0 --port 8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
